name: osv-scanner

on:
  pull_request:
    branches: [master]

concurrency:
  group: osv-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  osv-scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: osv-scanner
        uses: google/osv-scanner-action@v2.3.8
        with:
          scan-args: |-
            --recursive
